role = ["admins", "tutors", "students"]
permissions_list = {
    1: {
        "post": [2, 3, 4, 5, 6, 7, 8],
        "put": [2, 3, 4, 5, 6, 7, 8],
        "get": [2, 3, 4, 5, 6, 7, 8],
        "delete": [2, 3, 4, 5, 6, 7, 8],
        "admins": [2, 5, 6],
        "tutors": [3, 7],
        "students": [4, 8],
    },
    2: {
        "post": [3, 4, 5, 6, 7, 8],
        "put": [2, 3, 4, 5, 6, 7, 8],
        "get": [3, 4, 5, 6, 7, 8],
        "delete": [3, 4, 5, 6, 7, 8],
        "admins": [5, 6],
        "tutors": [3, 7],
        "students": [4, 8],
    },
    3: {
        "post": [3],
        "put": [3],
        "get": [4],
        "delete": [],
        "admins": [],
        "tutors": [],
        "students": [4],
    },
    4: {
        "post": [4],
        "put": [4],
        "get": [],
        "delete": [],
        "admins": [],
        "tutors": [],
        "students": [],
    },
    5: {
        "post": [6, 7, 8],
        "put": [5, 6, 7, 8],
        "get": [6, 7, 8],
        "delete": [6, 7, 8],
        "admins": [6],
        "tutors": [7],
        "students": [8],
    },
    6: {
        "post": [7, 8],
        "put": [6, 7, 8],
        "get": [7, 8],
        "delete": [7, 8],
        "admins": [],
        "tutors": [7],
        "students": [8],
    },
    7: {
        "post": [],
        "put": [7],
        "get": [7, 8],
        "delete": [],
        "admins": [],
        "tutors": [],
        "students": [8],
    },
    8: {
        "post": [8],
        "put": [8],
        "get": [8],
        "delete": [],
        "admins": [],
        "tutors": [],
        "students": [],
    },
}


course_permission_list = {
    "standard": {
        "post": [1, 2],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2],
        "delete": [1, 2],
    },
    "subject": {
        "post": [1, 2],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2],
        "delete": [1, 2],
    },
    "topic": {
        "post": [1, 2, 3],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2, 3],
        "delete": [1, 2, 3],
    },
    "subtopic": {
        "post": [1, 2, 3],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2, 3],
        "delete": [1, 2, 3],
    },
    "content": {
        "post": [1, 2, 3],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2, 3],
        "delete": [1, 2, 3],
    },
    "learning_outcome": {
        "post": [1, 2],
        "get": [1, 2, 3, 4, 5, 6, 7, 8],
        "put": [1, 2],
        "delete": [1, 2],
    },
}
