# Generated by Django 3.1 on 2022-03-03 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(max_length=50)),
                ('school_head', models.CharField(default='', max_length=50)),
                ('school_code', models.CharField(max_length=8)),
                ('classes', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('pin', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('authorized_by', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='AdminLocal',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.person',),
        ),
        migrations.CreateModel(
            name='StudentLocal',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Student',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.person',),
        ),
        migrations.CreateModel(
            name='SuperAdminLocal',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Superadmin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.person',),
        ),
        migrations.CreateModel(
            name='TutorLocal',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Tutor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.person',),
        ),
    ]
