# Generated by Django 3.1 on 2022-05-13 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_standard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(null=True, upload_to='image/avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
