# Generated by Django 3.1 on 2022-03-03 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField()),
                ('txn_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('otp_status', models.CharField(choices=[('Intialize', 'Intialize'), ('Progress', 'Progress'), ('Complete', 'Complete')], default='Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.PositiveIntegerField(default=1, unique=True)),
                ('role_name', models.CharField(choices=[('Super Admin', 'SuperAdmin'), ('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Student', 'Student'), ('Super Admin', 'SuperAdmin'), ('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Student', 'Student'), ('Content Manager', 'Content Manager'), ('Content Manager', 'Content Manager')], default='Super Admin', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('school_code', models.CharField(blank=True, editable=False, max_length=50)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=12, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('student_id', models.CharField(blank=True, editable=False, max_length=150)),
                ('standard', models.CharField(blank=True, max_length=10, null=True)),
                ('school_id', models.CharField(blank=True, max_length=40, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100)),
                ('language_comfortable_with', models.CharField(blank=True, max_length=100)),
                ('learning_disability', models.CharField(blank=True, max_length=100)),
                ('subjects_of_interest', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.CharField(blank=True, max_length=100)),
                ('specific_health_issue_or_concern', models.CharField(blank=True, max_length=100)),
                ('name_of_caregiver', models.CharField(blank=True, max_length=100)),
                ('name_of_wellness_counseller', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Discarded', 'Discarded')], default='Pending', max_length=15, verbose_name='Student Status')),
                ('school_name', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('login_otp', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('learning_domain', models.TextField(blank=True, null=True)),
                ('password_creation_token', models.TextField(blank=True, null=True, unique=True)),
                ('reset_password_token', models.TextField(blank=True, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
