# Generated by Django 3.1 on 2022-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='standard',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
