# Generated by Django 3.1 on 2022-05-11 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220429_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='image/avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.profile_avatar'),
        ),
    ]
